# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Documenti/LEZIONI/Digital Electronic System Design/Project/DAW/DAW.srcs/sources_1/bd/bd_DAW/ip/bd_DAW_proc_sys_reset_1_0/bd_DAW_proc_sys_reset_1_0.xci
# IP: The module: 'bd_DAW_proc_sys_reset_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Documenti/LEZIONI/Digital Electronic System Design/Project/DAW/DAW.gen/sources_1/bd/bd_DAW/ip/bd_DAW_proc_sys_reset_1_0/bd_DAW_proc_sys_reset_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_DAW_proc_sys_reset_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Documenti/LEZIONI/Digital Electronic System Design/Project/DAW/DAW.gen/sources_1/bd/bd_DAW/ip/bd_DAW_proc_sys_reset_1_0/bd_DAW_proc_sys_reset_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_DAW_proc_sys_reset_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Documenti/LEZIONI/Digital Electronic System Design/Project/DAW/DAW.gen/sources_1/bd/bd_DAW/ip/bd_DAW_proc_sys_reset_1_0/bd_DAW_proc_sys_reset_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_DAW_proc_sys_reset_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/Documenti/LEZIONI/Digital Electronic System Design/Project/DAW/DAW.srcs/sources_1/bd/bd_DAW/ip/bd_DAW_proc_sys_reset_1_0/bd_DAW_proc_sys_reset_1_0.xci
# IP: The module: 'bd_DAW_proc_sys_reset_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Documenti/LEZIONI/Digital Electronic System Design/Project/DAW/DAW.gen/sources_1/bd/bd_DAW/ip/bd_DAW_proc_sys_reset_1_0/bd_DAW_proc_sys_reset_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_DAW_proc_sys_reset_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Documenti/LEZIONI/Digital Electronic System Design/Project/DAW/DAW.gen/sources_1/bd/bd_DAW/ip/bd_DAW_proc_sys_reset_1_0/bd_DAW_proc_sys_reset_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_DAW_proc_sys_reset_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Documenti/LEZIONI/Digital Electronic System Design/Project/DAW/DAW.gen/sources_1/bd/bd_DAW/ip/bd_DAW_proc_sys_reset_1_0/bd_DAW_proc_sys_reset_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_DAW_proc_sys_reset_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
