# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pins.xdc

# Block Designs: bd/bd_DAW/bd_DAW.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_DAW || ORIG_REF_NAME==bd_DAW} -quiet] -quiet

# IP: bd/bd_DAW/ip/bd_DAW_clk_wiz_0_0/bd_DAW_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_DAW_clk_wiz_0_0 || ORIG_REF_NAME==bd_DAW_clk_wiz_0_0} -quiet] -quiet

# IP: bd/bd_DAW/ip/bd_DAW_proc_sys_reset_0_0/bd_DAW_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_DAW_proc_sys_reset_0_0 || ORIG_REF_NAME==bd_DAW_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/bd_DAW/ip/bd_DAW_proc_sys_reset_1_0/bd_DAW_proc_sys_reset_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_DAW_proc_sys_reset_1_0 || ORIG_REF_NAME==bd_DAW_proc_sys_reset_1_0} -quiet] -quiet

# IP: bd/bd_DAW/ip/bd_DAW_AXI4Stream_UART_0_0/bd_DAW_AXI4Stream_UART_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_DAW_AXI4Stream_UART_0_0 || ORIG_REF_NAME==bd_DAW_AXI4Stream_UART_0_0} -quiet] -quiet

# IP: bd/bd_DAW/ip/bd_DAW_packetizer_0_0/bd_DAW_packetizer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_DAW_packetizer_0_0 || ORIG_REF_NAME==bd_DAW_packetizer_0_0} -quiet] -quiet

# IP: bd/bd_DAW/ip/bd_DAW_depacketizer_0_0/bd_DAW_depacketizer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_DAW_depacketizer_0_0 || ORIG_REF_NAME==bd_DAW_depacketizer_0_0} -quiet] -quiet

# IP: bd/bd_DAW/ip/bd_DAW_edge_detector_0_0/bd_DAW_edge_detector_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_DAW_edge_detector_0_0 || ORIG_REF_NAME==bd_DAW_edge_detector_0_0} -quiet] -quiet

# IP: bd/bd_DAW/ip/bd_DAW_debouncer_0_0/bd_DAW_debouncer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_DAW_debouncer_0_0 || ORIG_REF_NAME==bd_DAW_debouncer_0_0} -quiet] -quiet

# IP: bd/bd_DAW/ip/bd_DAW_edge_detector_1_0/bd_DAW_edge_detector_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_DAW_edge_detector_1_0 || ORIG_REF_NAME==bd_DAW_edge_detector_1_0} -quiet] -quiet

# IP: bd/bd_DAW/ip/bd_DAW_debouncer_1_0/bd_DAW_debouncer_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_DAW_debouncer_1_0 || ORIG_REF_NAME==bd_DAW_debouncer_1_0} -quiet] -quiet

# IP: bd/bd_DAW/ip/bd_DAW_mute_controller_0_0/bd_DAW_mute_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_DAW_mute_controller_0_0 || ORIG_REF_NAME==bd_DAW_mute_controller_0_0} -quiet] -quiet

# IP: bd/bd_DAW/ip/bd_DAW_volume_controller_0_0/bd_DAW_volume_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_DAW_volume_controller_0_0 || ORIG_REF_NAME==bd_DAW_volume_controller_0_0} -quiet] -quiet

# IP: bd/bd_DAW/ip/bd_DAW_moving_average_filter_0_0/bd_DAW_moving_average_filter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_DAW_moving_average_filter_0_0 || ORIG_REF_NAME==bd_DAW_moving_average_filter_0_0} -quiet] -quiet

# XDC: d:/Documenti/LEZIONI/Digital Electronic System Design/Project/DAW/DAW.gen/sources_1/bd/bd_DAW/bd_DAW_ooc.xdc
