# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/SimoGein/Desktop/DESD/basys3_master_xdc.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AXI4Stream_UART_0_0/design_1_AXI4Stream_UART_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_AXI4Stream_UART_0_0 || ORIG_REF_NAME==design_1_AXI4Stream_UART_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_proc_sys_reset_0_1/design_1_proc_sys_reset_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_1 || ORIG_REF_NAME==design_1_proc_sys_reset_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_packetizer_0_0/design_1_packetizer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_packetizer_0_0 || ORIG_REF_NAME==design_1_packetizer_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_depacketizer_0_0/design_1_depacketizer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_depacketizer_0_0 || ORIG_REF_NAME==design_1_depacketizer_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_debouncer_0_0/design_1_debouncer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_debouncer_0_0 || ORIG_REF_NAME==design_1_debouncer_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_edge_detector_0_0/design_1_edge_detector_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_edge_detector_0_0 || ORIG_REF_NAME==design_1_edge_detector_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_debouncer_0_1/design_1_debouncer_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_debouncer_0_1 || ORIG_REF_NAME==design_1_debouncer_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_edge_detector_0_1/design_1_edge_detector_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_edge_detector_0_1 || ORIG_REF_NAME==design_1_edge_detector_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mute_controller_0_0/design_1_mute_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mute_controller_0_0 || ORIG_REF_NAME==design_1_mute_controller_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_volume_controller_0_0/design_1_volume_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_volume_controller_0_0 || ORIG_REF_NAME==design_1_volume_controller_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mobile_mean_filter_0_0/design_1_mobile_mean_filter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mobile_mean_filter_0_0 || ORIG_REF_NAME==design_1_mobile_mean_filter_0_0} -quiet] -quiet

# XDC: c:/Users/SimoGein/Desktop/DESD/DESD-LAB3/project_3.gen/sources_1/bd/design_1/design_1_ooc.xdc
